---
# https://docs.travis-ci.com/user/multi-os/
matrix:
  include:
    - os: osx
      language: generic
      env:
        - TARGET=localhost
    - os: linux
      dist: trusty
      language: python
      python: 2.7
      services:
        - docker
      addons:
        apt:
          packages:
          - python-pip
      before_script:
        - docker run -it -d --name container python:2 /bin/bash
        # Workaround: Docker connection plugin of Ansible requires that
        # Python is installed at specified path(/usr/bin/python) in the target container
        - if [ ! -e /usr/bin/python ]; then docker exec container ln -s /usr/local/bin/python /usr/bin/python; fi
      after_script:
        - docker rm -f container
      env:
        - TARGET=container

sudo: required

install:
  - sudo pip install -e "git+https://github.com/audreyr/cookiecutter.git#egg=cookiecutter"

script:
  - cookiecutter --replay --config-file tests/cookiecutterrc .
  - cd test_project
  - sudo pip install -r requirements.txt
  - ansible-galaxy install -r role_requirements.yml
  - ansible-playbook playbooks/buildenv.yml -i tests/inventory -l ${TARGET} -vvvv
  - bundle install
  - bundle exec rake spec SPEC_TARGET=${TARGET}
