---
# https://docs.travis-ci.com/user/multi-os/
os: linux
dist: trusty
language: python
python: 2.7
sudo: required

services:
  - docker

addons:
  apt:
    packages:
    - python-pip
install:
  - sudo pip install -e "git+https://github.com/audreyr/cookiecutter.git#egg=cookiecutter"

# Check whether packer build works properly on generated project.
script:
  - cookiecutter --replay --config-file tests/cookiecutterrc .
  - cd test_project
  - pip install ansible
  - ansible-galaxy install -r role_requirements.yml
  - wget https://releases.hashicorp.com/packer/0.9.0/packer_0.9.0_linux_amd64.zip && unzip packer_0.9.0_linux_amd64.zip
  - ./packer build platforms/docker/alpine.json
  - docker run -it -d --name container fgtatsuro/test_project:alpine-3.3
after_script:
  - docker rm -f container

