---
# https://docs.travis-ci.com/user/multi-os/
matrix:
  include:
    - os: osx
      language: generic
    - os: linux
      dist: trusty
      language: python
      python: 2.7

# This role needs sudo, thus we can't use the new container infrastructure
# sudo: false
sudo: required

install:
  - sudo pip install -e "git+https://github.com/audreyr/cookiecutter.git#egg=cookiecutter"

script:
  - cookiecutter --replay --config-file tests/cookiecutterrc .
  - cd test_project
  # TODO: some testing
